image:
  - Visual Studio 2015 
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug

build:
  verbosity: detailed

environment:
  matrix:
    - GENERATOR_ARCH: Win32
    - GENERATOR_ARCH: x64

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. 
    -A %GENERATOR_ARCH% 
    -DSAMPLES_BUILD=ON 
    -DTESTS_BUILD=ON
    -DSAMPLES_BUILD_ONLY_DYNAMIC=ON 
    -DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON 
    -DTESTS_BUILD_ONLY_DYNAMIC=ON 
    -DTESTS_BUILD_WITH_LOCAL_VULKAN_HPP=ON
  - cmake --build . --config %CONFIGURATION%
