os:
  - Visual Studio 2017

build:
  verbosity: detailed

configuration:
  - Debug

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017
      RAW_PLATFORM: x86
    - GENERATOR: Visual Studio 15 2017 Win64
      RAW_PLATFORM: amd64


install:
  - git submodule update --init --recursive


before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %RAW_PLATFORM%
  - cd C:\projects\Vulkan-Hpp


build_script:
  - mkdir appveyor-build
  - cd appveyor-build
  - cmake .. "-G%GENERATOR%"
  - cmake --build . --config %CONFIGURATION%

test_script:
  - "%CONFIGURATION%\\VulkanHppGenerator"
  - ps: Write-Output "#include ""vulkan.hpp""" | Out-File -FilePath test.cpp
  - ps: Write-Output "int myCreateInstance()" | Out-File -FilePath test.cpp -Append
  - ps: Write-Output "{" | Out-File -FilePath test.cpp -Append
  - ps: Write-Output "    vk::Instance inst;" | Out-File -FilePath test.cpp -Append
  - ps: Write-Output "    auto const inst_info = vk::InstanceCreateInfo();" | Out-File -FilePath test.cpp -Append
  - ps: Write-Output "    vk::Result result = vk::createInstance(&inst_info, nullptr, &inst);" | Out-File -FilePath test.cpp -Append
  - ps: Write-Output "    return static_cast<int> (result);" | Out-File -FilePath test.cpp -Append
  - ps: Write-Output "}" | Out-File -FilePath test.cpp -Append
  - cl.exe -I../vulkan -I../Vulkan-Headers/include /EHsc -c test.cpp
