configuration:
  - Debug

build:
  verbosity: detailed

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR_ARCH: Win32
      CXX_STANDARD: 11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR_ARCH: x64
      CXX_STANDARD: 11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR_ARCH: Win32
      CXX_STANDARD: 11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR_ARCH: x64
      CXX_STANDARD: 11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR_ARCH: Win32
      CXX_STANDARD: 11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR_ARCH: x64
      CXX_STANDARD: 11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR_ARCH: x64
      CXX_STANDARD: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR_ARCH: x64
      CXX_STANDARD: 17
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR_ARCH: x64
      CXX_STANDARD: 20

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. 
    -A %GENERATOR_ARCH% 
    -DSAMPLES_BUILD=ON 
    -DTESTS_BUILD=ON
    -DSAMPLES_BUILD_ONLY_DYNAMIC=ON 
    -DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON 
    -DTESTS_BUILD_ONLY_DYNAMIC=ON 
    -DTESTS_BUILD_WITH_LOCAL_VULKAN_HPP=ON
    -DCMAKE_CXX_STANDARD=%CXX_STANDARD%
  - cmake --build . --config %CONFIGURATION%
