version = 1

# ---- Repo infrastructure and documentation ----

[[annotations]]
path = [
    ".gitmodules",
    "CMakeLists.txt",
    "CMakePresets.json",
    "VulkanHpp.natvis",

    ".github/workflows/**",
    "docs/**",
    "generator/.clang-format_*",
    "RAII_Samples/**",
    "tests/**",
]
SPDX-FileCopyrightText = "2026 NVIDIA Corporation"
SPDX-License-Identifier = "Apache-2.0"
