
name: CI Ubuntu 20

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash
    
    strategy:
      matrix:
        compiler: [clang++-10, clang++-11, clang++-12, g++-10]
        cpp_standard: [11, 14, 17, 20]
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install libraries
      run: sudo apt update && sudo apt install libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

    - name: Install Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.11.0

    - name: Build
      run: |
        cmake -B build/${{matrix.cpp_standard}}/${{matrix.build_type}} -GNinja \
          -DVULKAN_HPP_SAMPLES_BUILD=ON                                        \
          -DVULKAN_HPP_SAMPLES_BUILD_ONLY_DYNAMIC=ON                           \
          -DVULKAN_HPP_TESTS_BUILD=ON                                          \
          -DVULKAN_HPP_TESTS_BUILD_ONLY_DYNAMIC=ON                             \
          -DVULKAN_HPP_BUILD_WITH_LOCAL_VULKAN_HPP=ON                          \
          -DVULKAN_HPP_PRECOMPILE=OFF                                          \
          -DVULKAN_HPP_RUN_GENERATOR=ON                                        \
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}}                            \
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}}                        \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build/${{matrix.cpp_standard}}/${{matrix.build_type}} --parallel

