name: CI Ubuntu

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  push:
    #branches: ["master"]
    branches: ["*"]

jobs:
  update-vulkan-headers:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug]
        cxx_compiler: [g++-9]
        cxx_standard: [11]

    steps:
    - uses: actions/checkout@v2
    
    - name: Install libraries
      run: sudo apt install libgl-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev clang-format-12

    - name: Update Submodules
      run: |
        git submodule update --init --recursive
        cd Vulkan-Headers
        VK_HEADER_GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        git checkout $VK_HEADER_GIT_TAG
        echo "VK_HEADER_GIT_TAG=$VK_HEADER_GIT_TAG" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
            -DSAMPLES_BUILD=OFF
            -DSAMPLES_BUILD_ONLY_DYNAMIC=ON
            -DSAMPLES_BUILD_WITH_LOCAL_VULKAN_HPP=ON
            -DTESTS_BUILD=OFF
            -DTESTS_BUILD_ONLY_DYNAMIC=ON
            -DTESTS_BUILD_WITH_LOCAL_VULKAN_HPP=ON
            -DVULKAN_HPP_RUN_GENERATOR=ON
            -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}}
            -DCMAKE_CXX_STANDARD=${{matrix.cxx_standard}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Commit changes
      run: |
        git config user.name "GitHub"
        git config user.email "noreply@github.com"
        git commit -am "Update Vulkan-Headers to $VK_HEADER_GIT_TAG" || echo 'No commit necessary!'
        git clean -xf

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update Vulkan-Headers
        title: Update Vulkan-Headers
        branch: update-vulkan-headers-pr
        base: ${{ github.head_ref }}
